### ISSUE TITLE
Deprecation warning when building: “'init(bytes:)' is deprecated”

### ISSUE THREAD

**Issue by roryokane** [chbrown/macos-pasteboard#1]
When I ran `make install`, I saw a deprecation warning in part of the output:

~~~
xcrun -sdk macosx swiftc pbv.swift -O -o pbv
pbv.swift:5:15: warning: 'init(bytes:)' is deprecated: use `init(_:)` instead
let newline = Data(bytes: [0x0A] as [UInt8])
              ^
~~~

The warning refers to this line:

https://github.com/chbrown/macos-pasteboard/blob/13ae28e538769be7c3011eb66bf79c7da36bc863/pbv.swift#L5

My computer has Swift version 5.0.1 installed, according to `swift --version`.

`pbv` still works despite the warning.

**Comment by chbrown** [comment]
Ha, yeah, and the fix has been sitting in my unstaged changes for a while. I didn't realize other people used this. Cool.
